postgres:
    image: postgres
    expose: 
        - "5432"
    environment:
        - POSTGRESQL_USER=kaiwa
        - POSTGRESQL_PASSWORD=hello

# Somehow need to add users to server
ldap:
    image: nickstenning/slapd
    command: /etc/service/slapd/run
    expose:
        - "389"
    environment:
        - LDAP_DOMAIN=localhost
        - LDAP_ORGANISATION=cadair
        - LDAP_ROOTPASS=hello

ldap-configure:
    build: slapd-configure/
    links: 
        - ldap:ldap

prosody:
    image: sebu77/kaiwa-server
    ports:
        - "5269:5269"
        - "5280:5280"
        - "5281:5281"
        - "3478:3478"
    links:
        - postgres:postgres
        - ldap:ldap
    environment:
        - XMPP_DOMAIN=localhost
        - DB_NAME=kaiwa
        - DB_USER=kaiwa
        - DB_PWD=hello
        - LDAP_USER_BASE=ou=users,dc=cadair
        - LDAP_GROUP_BASE=ou=groups,dc=cadair
        - LDAP_DN=cn=admin,dc=cadair
        - LDAP_PWD=hello
        - LDAP_GROUP=cadair

kaiwa:
    image: sebu77/kaiwa
    ports:
        - "8821:8000"
    links:
        - ldap:ldap
    environment:
        - VIRTUAL_HOST=localhost
        - VIRTUAL_PORT=80
        - XMPP_NAME=cadair
        - XMPP_DOMAIN=localhost
        - XMPP_WSS=ws://localhost:5280/xmpp-websocket
        - XMPP_MUC=chat.localhost
        - XMPP_STARTUP=groupchat/home%40chat.localhost
        - XMPP_ADMIN=admin
        - LDAP_USER_BASE=ou=users,dc=cadair
        - LDAP_GROUP_BASE=ou=groups,dc=cadair
        - LDAP_DN=cn=admin,dc=cadair
        - LDAP_PWD=hello
        - LDAP_GROUP=cadair
